# Generated by Django 4.2 on 2023-05-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=models.TextField(),
        ),
    ]
